### ISSUE TITLE
Fix user groups script call in base recipe

### ISSUE THREAD

**Issue by swvanbuuren** [swvanbuuren/simple-cdd-yaml-recipes#1]
The following action in the recipe [base.yaml](https://github.com/swvanbuuren/simple-cdd-yaml-recipes/blob/master/recipes/base.yaml) should user the script `setup_user_groups.sh` instead of `add_sudoers.sh`

```yaml
  - action: run
    description: Add {{username}} to several groups
    substitutions:
      username: {{username}}
      groups: admin,adm,dialout,cdrom,plugdev,power,audio,dip,video,staff,shared,sudo
    script: scripts/add_sudoer.sh
```
