### ISSUE TITLE
Add scripting for installing snes9x

### ISSUE THREAD

**Issue by swvanbuuren** [swvanbuuren/simple-cdd-yaml-recipes#19]
It would be nice to have a script available to install the Snes9x AppImage.

There already are existing instructions available:
```yaml
  - action: apt
    description: Required packages for using AppImages
    packages:
      - fuse3

  - action: run
    description: Download Snes9x AppImage
    user: {{username}}
    command: >
      mkdir -p /home/{{username}}/.local/bin &&
      wget -O /home/{{username}}/.local/bin/Snes9x.AppImage 
      https://github.com/snes9xgit/snes9x/releases/download/1.62.3/Snes9x-1.62.3-x86_64.AppImage &&
      chmod +x /home/{{username}}/.local/bin/Snes9x.AppImage
```

Request to include this as a single script into this repository.
