### ISSUE TITLE
Add overlay with ruff configuration

### ISSUE THREAD

**Issue by swvanbuuren** [swvanbuuren/simple-cdd-yaml-recipes#25]
[`ruff`](https://github.com/astral-sh/ruff) is a very fast and flexible python linter, written in rust.

Provide an overlay with [`ruff`](https://github.com/astral-sh/ruff) configuration settings. Preferably, the configuration file is stored in `$HOME/.config/ruff/ruff.toml`.

Contents of the configuration file:
```toml
# Same as Black.
line-length = 80
indent-width = 4

[lint]
select = ["E", "F", "W", "N", "D", "UP", "PL"]
ignore = ["D400", "D415"]

[format]
# Like Black, use double quotes for strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
```
