### ISSUE TITLE
Add virtualenvwrapper setup actions

### ISSUE THREAD

**Issue by swvanbuuren** [swvanbuuren/simple-cdd-yaml-recipes#8]
Propose to add `virtuallenvwrapper` for easy activation of python virtual environments.

Required debian package: `virtualenvwrapper` and configuration of some environment variables and calling of scripts:

Required addition to the recipe would be

```yaml
- action: apt
  description: Install wrapper for virtualenv to easily manage virtualenvs
  packages:
    - virtualenvwrapper

- action: run
  description: Configure virtualenvwrapper
  command: > 
    _OUT=/home/{{username}}/.bashrc;
    _VENV=/home/{{username}}/.venv;
    mkdir -p $_VENV;
    echo "\nexport WORKON_HOME=$_VENV\n" >> $_OUT;
    echo ". /usr/share/virtualenvwrapper/virtualenvwrapper.sh\n" >> $_OUT;
```
